[workspace]
members = [
    "program",
    "script",
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "0.7.7"
fuel-zkvm-primitives-prover = { path = "../../../zkvm-primitives/fuel-zkvm-primitives-prover" }
fuel-zkvm-primitives-input-provider = { path = "../../../zkvm-primitives/fuel-zkvm-primitives-input-provider" }

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"
panic = "abort"
