[workspace]
members = [
    "program",
    "script",
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "0.7.7"
prover = { path = "../../../zkvm-primitives/prover" }
input-provider = { path = "../../../zkvm-primitives/input-provider" }
fuel-fixture = { path = "../../../zkvm-primitives/example", package = "example" }

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"
panic = "abort"
